const chara_setting = {
    tamago: {
        path: "assets/img/chara/tamago.png",
        scale: 1,
        frameW: 32,
        frameH: 32,
        frameStart: 0,
        frameEnd: 0,
        bodySize: {
          w: 40,
          h: 60,
        },
        move:false,
    },
    chana: {
        path: "assets/img/chara/chana_ss.png",
        scale: 2,
        frameW: 32,
        frameH: 32,
        frameStart: 0,
        frameEnd: 3,
        bodySize: {
            w: 20,
            h: 20,
        },
        move:true,
    },
    masara: {
        path: "assets/img/chara/masara_ss.png",
        scale: 2,
        frameW: 32,
        frameH: 32,
        frameStart: 0,
        frameEnd: 3,
        bodySize: {
            w: 20,
            h: 30,
        },
        move:true,
    },
    makiko: {
        path: "assets/img/chara/makiko_ss.png",
        scale: 2,
        frameW: 32,
        frameH: 32,
        frameStart: 0,
        frameEnd: 1,
        bodySize: {
            w: 20,
            h: 30,
        },
        move:true,
    },
    makoto: {
        path: "assets/img/chara/makoto_ss.png",
        scale: 1,
        frameW: 64,
        frameH: 64,
        frameStart: 0,
        frameEnd: 3,
        bodySize: {
            w: 40,
            h: 60,
        },
        move:true,
    },
    rancia: {
        path: "assets/img/chara/rancia_ss.png",
        scale: 2,
        frameW: 32,
        frameH: 32,
        frameStart: 0,
        frameEnd: 1,
        bodySize: {
            w: 20,
            h: 30,
        },
        move:true,
    },
    taki: {
        path: "assets/img/chara/taki_ss.png",
        scale: 2,
        frameW: 32,
        frameH: 32,
        frameStart: 0,
        frameEnd: 3,
        bodySize: {
            w: 20,
            h: 30,
        },
        move:true,
    },
    tanikou: {
        path: "assets/img/chara/tanikou_kari.png",
        scale: 2,
        frameW: 28,
        frameH: 32,
        frameStart: 0,
        frameEnd: 3,
        bodySize: {
            w: 20,
            h: 30,
        },
        move:true,
    },
    konataro: {
        path: "assets/img/chara/konataro_ss.png",
        scale: 2,
        frameW: 32,
        frameH: 32,
        frameStart: 0,
        frameEnd: 1,
        bodySize: {
            w: 20,
            h: 30,
        },
        move:true,
    },
    watari: {
        path: "assets/img/chara/watari_ss.png",
        scale: 2,
        frameW: 32,
        frameH: 32,
        frameStart: 0,
        frameEnd: 3,
        bodySize: {
            w: 20,
            h: 30,
        },
        move:true,
    },
    chachamaru: {
        path: "assets/img/chara/chachamaru_ss.png",
        scale: 2,
        frameW: 32,
        frameH: 32,
        frameStart: 0,
        frameEnd: 3,
        bodySize: {
            w: 20,
            h: 30,
        },
        move:true,
    },
    dairi: {
        path: "assets/img/chara/dairi_ss.png",
        scale: 2,
        frameW: 32,
        frameH: 32,
        frameStart: 0,
        frameEnd: 3,
        bodySize: {
            w: 20,
            h: 30,
        },
        move:true,
    },
    erishia: {
        path: "assets/img/chara/erishia_ss.png",
        scale: 2,
        frameW: 32,
        frameH: 32,
        frameStart: 0,
        frameEnd: 3,
        bodySize: {
            w: 20,
            h: 30,
        },
        move:true,
    },
    taguchi: {
        path: "assets/img/chara/taguchi_ss.png",
        scale: 2,
        frameW: 32,
        frameH: 32,
        frameStart: 0,
        frameEnd: 3,
        bodySize: {
            w: 20,
            h: 30,
        },
        move:true,
    },
    haka: {
        path: "assets/img/chara/haka.png",
        scale: 2,
        frameW: 32,
        frameH: 32,
        frameStart: 0,
        frameEnd: 0,
        bodySize: {
            w: 20,
            h: 30,
        },
        move:false,
    },
};

export default chara_setting;